name: articles

networks:
  default:
    name: articles

volumes:
  articles-postgres:
  articles-loki:
  articles-grafana:
  articles-prometheus:

services:
  postgres:
    container_name: articles-postgres
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - articles-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  redis:
    container_name: articles-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'

  loki:
    container_name: 'articles-loki'
    image: grafana/loki
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - articles-loki:/loki
    command : --config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: 'articles-prometheus'
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - articles-prometheus:/prometheus

  jaeger:
    container_name: articles-jaeger
    image: jaegertracing/all-in-one
    ports:
      - '6831:6831/udp'  # Agent Thrift Compact
      - '6832:6832/udp'  # Agent Thrift Binary
      - '5778:5778'      # Agent Configuration
      - '16686:16686'    # UI
      - '14268:14268'    # Collector HTTP
      - '14250:14250'    # Collector gRPC
      - '4317:4317'      # OTLP gRPC (OpenTelemetry Protocol)
      - '4318:4318'      # OTLP HTTP (OpenTelemetry Protocol)
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  grafana:
    container_name: articles-grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - articles-grafana:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
