name: articles

networks:
  default:
    name: articles

volumes:
  articles-postgres:
  articles-loki:
  articles-grafana:
  articles-prometheus:
  articles-minio:
  articles-redis-insight:

services:
  postgres:
    container_name: articles-postgres
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - articles-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mailhog:
    container_name: articles-mailhog
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  redis:
    container_name: articles-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: articles-redis-insight
    restart: unless-stopped
    ports:
      - '5540:5540'
    volumes:
      - articles-redis-insight:/data
    depends_on:
      - redis

  loki:
    container_name: articles-loki
    image: grafana/loki
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - articles-loki:/loki
    command: --config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: articles-prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - articles-prometheus:/prometheus

  jaeger:
    container_name: articles-jaeger
    image: jaegertracing/all-in-one
    ports:
      - '6831:6831/udp'  # Agent Thrift Compact
      - '6832:6832/udp'  # Agent Thrift Binary
      - '5778:5778'      # Agent Configuration
      - '16686:16686'    # UI
      - '14268:14268'    # Collector HTTP
      - '14250:14250'    # Collector gRPC
      - '4317:4317'      # OTLP gRPC (OpenTelemetry Protocol)
      - '4318:4318'      # OTLP HTTP (OpenTelemetry Protocol)
    environment:
      - COLLECTOR_OTLP_ENABLED:true

  grafana:
    container_name: articles-grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - articles-grafana:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  minio:
    container_name: articles-minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server --console-address ':9001' /data/
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - articles-minio:/data

  api:
    build:
      context: .
    container_name: articles-api
    image: articles-api:latest
    ports:
      - '7777:7777'
    environment:
      ASPNETCORE_URLS: http://+:7777
      ConnectionStrings__Postgres: User ID=postgres;Password=postgres;Host=articles-postgres;Port=5432;Database=postgres;
      ConnectionStrings__Redis: articles-redis:6379
      ConnectionStrings__Loki: http://articles-loki:3100
      ConnectionStrings__Jaeger: http://articles-jaeger:4317
      HealthCheckOptions__PrometheusEndpoint: http://articles-prometheus:9090/-/healthy
      HealthCheckOptions__LokiEndpoint: http://articles-loki:3100/ready
      HealthCheckOptions__JaegerEndpoint: http://articles-jaeger:16686
      HealthCheckOptions__MinioEndpoint: http://articles-minio:9000/minio/health/ready
      SmtpClientOptions__Host: mailhog
      MinioOptions__Endpoint: articles-minio:9000



