scrape_configs:
  - job_name : articles-scrape
    scrape_interval : 10s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - host.docker.internal:5200
        labels:
          app: articles

      - targets:
          - articles-api:5232
        labels:
          app: articles-docker
